name: "Docker Build"
on:
  # build a daily dev image  
  schedule:
    - cron: "42 6 * * *"
  push:
    tags:
      # todo: update for 1.0
      - 0.*
permissions:
  contents: read

jobs:
  Publish:
    permissions:
      id-token: write
    strategy:
      matrix:
        image:
          - c7n
          - c7n-org
          - mailer
          - policystream
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      - name: ${{ matrix.image }} build and push
        uses: ./.github/composites/docker-build-push
        env:
          HUB_USER: c7nbuild
          HUB_TOKEN: ${{ secrets.DOCKER_CI_HUB_TOKEN }}
        with:
          name: ${{ matrix.image }}
          push: true
          platforms: linux/arm64,linux/amd64

      - name: Notify Slack
        uses: ravsamhq/notify-slack-action@bca2d7f5660b833a27bda4f6b8bef389ebfefd25 # v2
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_CI_HOOK }}
        with:
          status: ${{ job.status }}
          notification_title: "{workflow}:{job} has {status_message}"
          message_format: "{emoji} *{workflow}:{job}* {status_message} in <{repo_url}|{repo}>"
          footer: "Logs <{run_url}|{job}>"
          notify_when: "failure,success"
